# Generated by Django 2.0.2 on 2020-02-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200208_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='student_class',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identity',
            field=models.CharField(choices=[('teacher', '管理员'), ('student', '用户')], default='student', max_length=50, verbose_name='身份'),
        ),
    ]
