# Generated by Django 2.0.2 on 2020-02-14 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0002_auto_20190708_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswerlog',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.PaperList', verbose_name='试卷'),
        ),
    ]
