# Generated by Django 2.0.2 on 2020-02-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0003_paperlist_random_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('选择题', '选择题'), ('判断题', '判断题'), ('多选题', '多选题'), ('简答题', '简答题')], default='选择题', max_length=20, verbose_name='题目类型'),
        ),
    ]
