# Generated by Django 2.0.2 on 2020-02-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0004_auto_20200213_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('单选题', '单选题'), ('判断题', '判断题'), ('多选题', '多选题'), ('简答题', '简答题')], default='单选题', max_length=20, verbose_name='题目类型'),
        ),
    ]
