# Generated by Django 2.0.2 on 2020-02-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0005_auto_20200213_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('xz', 'xz'), ('pd', 'pd'), ('mxz', 'mxz'), ('jd', 'jd')], default='xz', max_length=20, verbose_name='题目类型'),
        ),
    ]
