# Generated by Django 2.0.2 on 2020-02-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0006_auto_20200213_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('xz', '单选题'), ('pd', '判断题'), ('mxz', '多选题'), ('jd', '简答题')], default='xz', max_length=20, verbose_name='题目类型'),
        ),
    ]
