# Generated by Django 2.0.2 on 2020-02-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0008_auto_20200214_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperlist',
            name='jd_choice_num',
            field=models.IntegerField(default=0, verbose_name='简答题数'),
        ),
        migrations.AlterField(
            model_name='paperlist',
            name='jd_choice_score',
            field=models.IntegerField(default=0, verbose_name='简答分值'),
        ),
    ]
